import Products from "@/components/products/Products";
import ProtectedRoute from "@/components/ProtectedRoute";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "About page",
  description: "Generated by create next app",
};

const Product = async () => {
  const data = await fetch("https://dummyjson.com/products", { cache: "force-cache" });
  const products = await data.json()
  console.log(products);

  return (
    <ProtectedRoute>

  <Products data={products} />
    </ProtectedRoute>
  )
};

export default Product;
